### ISSUE TITLE
Implementar la funcionalidad para editar usuarios existentes(Front-End).

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#105]
Criterio de aceptación:

-La funcionalidad debe poder modificar todos los campos del usuario registrado dentro de la empresa.

**Comment by felipevega-dev** [comment]
Se pueden editar usuarios desde la nueva vista ![Image](https://github.com/user-attachments/assets/204f59dd-fb50-4070-94aa-ef4e21961f5c)
