### ISSUE TITLE
Crear formulario para registrar nuevos usuarios(Front-End).

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#107]
Se debe diseñar el formulario para poder registra los nuevos usuarios.

Criterio de aceptacion: 

-Se debe agregar los campos de la informacion personal de usuario como:

## Usuarios empleado:

- Correo electronico
- Apellido
- Telefono
- Contraseña

##Usuario cliente:

- Correo electronico
- Apellido
- Telefono
- Contraseña
- Nombre del supermercado
- Rut empresa
- Dirección facturación
- Dirección envió
- Preferencias de envío

**Comment by felipevega-dev** [comment]
Formulario para crear nuevos clientes o empleados
![Image](https://github.com/user-attachments/assets/abca6cd0-bc47-46d4-9d99-8a587d064ebc)
