### ISSUE TITLE
Base de datos (PostgreSQL): Documentar la estructura final de las tablas

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#11]

**Comment by javegaf** [comment]
Basándonos en el [script principal](https://drive.google.com/file/d/1ygqJ4j8coLL_2M4-DqWtke95mZF-b_Vp/view?usp=sharing) que luego se transformo en uno [adaptado a PostgreSQL](https://drive.google.com/file/d/1p085mDSk5a_xURN2YlAdcdVzyUOyXa5s/view?usp=drive_link) fue luego [modelado](https://drive.google.com/file/d/1nFa8qfjvZYHwBgDg1KLSa-AwR81sUPug/view?usp=drive_link) como referencia gráfica del mismo

**Comment by Mrempanada1** [comment]
Añadiendo el documento de la estructura final de las tablas
[Modelo de datos.docx](https://github.com/user-attachments/files/17875809/Modelo.de.datos.docx)
