### ISSUE TITLE
Desarrollar pagina generar reportes(Front-End).

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#124]
Se tiene que construir la estructura basica de la pagina Reportes. Esto es para que el usuario gerente financiero pueda visualizar esta información.

Criterios de aceptación:

-La estructura básica de la pagina tiene que tener la misma que esta diseñada en figma.
-Tiene que seguir el mismo layout que las demás paginas.
-Los colores tiene que seguir el mismo patron principal que marca el mockup.

**Comment by TopherHasashi** [comment]
Pagina agregada
