### ISSUE TITLE
Definir estructura de las tablas de la base de datos.

### ISSUE THREAD

**Issue by alecuevas660** [alecuevas660/Proyecto-sistema-web-de-despacho#2]
**Pre condición:** Debe existir un diseño previo que especifique las necesidades de información para la gestión general.

**Criterio de aceptación:** 
La tabla de productos debe contener las siguientes columnas:
- ID del Producto: Identificador único.
- Nombre: Nombre descriptivo del producto.
- Categoría: Categoría a la que pertenece el producto.
- Cantidad: Número de unidades disponibles.
- Cantidad mínimo: Cantidad minino por producto en stock.
- Fecha de Adición: Fecha en que se agregó el producto al inventario.

La tabla de ordenes debe contener las siguiente columnas:
- ID de la orden: Identificador único.
- Cliente: El nombre del cliente(supermercado).
- Estado: El estado actual de la orden.
- Dirección: Dirección del supermercado.
- Asignado: Asignado son los transportista encargado de la entrega. 

La tabla Usuarios debe contener las siguiente columnas:
- ID del usuario: Identificador único.
- Nombre: Nombre del usuario.
- Contraseña: Contraseña del usuario.
- Email: Email empresarial asignado al usuario.
- Rol: El que se le asocia al usuario.
- Estado: Muestra el estado del usuario.

**Comment by javegaf** [comment]
**Tarea terminada y respaldada en un archivo subido a drive** **([ScriptDDL.sql](https://drive.google.com/file/d/1p085mDSk5a_xURN2YlAdcdVzyUOyXa5s/view?usp=sharing))**
