### ISSUE TITLE
Backend (Django): 1. Definir estructura de las tablas de productos

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#5]

**Comment by javegaf** [comment]
Está lista la definición de la [tabla de productos, junto a toda la base de datos](https://drive.google.com/file/d/1kxVrSK4UofVyBehr-F5Ro2mKZSR3SzKu/view?usp=sharing), pero actualmente por un problema que se esta solucionando no se puede completar y creo que se debería catalogar como bloqueado por el momento.
**Se adjunta imagen del problema que se esta resolviendo**
![Image](https://github.com/user-attachments/assets/31503869-15d3-4aff-bb01-b4e062f39c71)
![Image](https://github.com/user-attachments/assets/93977b7f-3f95-491f-aecd-6412511c21bc)

**Comment by MoisesFigueroaDeveloper** [comment]
Para solucionar el problema se tiene que instalar postgres:

Para esto pueden instalarlos directamente desde la terminal usando los comando.

- brew install postgresql@15 --Para Mac Os

Para esto tendran que instalar homebrew en su equipo.

luego comprobar la version con psql --version

Si no aparece la version de postgres en la terminal tendrá que exportar PG al $PATH:

- export PATH="/opt/homebrew/opt/postgresql@17/bin:$PATH"

Y desde windows Tiene que instalar la app directamente, Es decir instalar el ejecutable y luego comprobar su version con psql --version
 
En el caso de windows si pasa lo mismo a no poder encontrar la version de postgres tendrá que exportarlo manualmente al PATH(local).
