### ISSUE TITLE
Diseñar el mockup de las vistas de la paginas.

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#69]
Se debe crear el diseño de la paginas para la dashboard y diseñar los componentes que contendrá en ellas.

Criterios de aceptación:

- Pagina para inicio de sesión.
- Pagina del resumen general de la empresa.
- Pagina de estado de inventario.
- Pagina de ordenes de despacho.
- Pagina de mapa de seguimiento.
- Pagina de descargas de reportes financieros.
- Pagina de gestión de usuarios.

**Comment by javegaf** [comment]
Las [evidencias de cada vista](https://drive.google.com/drive/folders/1qq4lKppFpJUdtNxCxDG9koeYSELtC50I?usp=sharing) están subidas al drive del proyecto en su propio apartado
