### ISSUE TITLE
Preparación y configuración del entorno de trabajo

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#70]

**Comment by javegaf** [comment]
Como no se comentó a grandes rasgos la evidencia que sustente el cierre del caso, las daré yo.
El asignado [felipevega-dev](https://github.com/felipevega-dev) realizo las tareas de preparación de los archivos y ambientes necesarios en el repositorio con los respectivos commits haciendo la separación de las partes lo mas claro posible para los desarrolladores.
![Image](https://github.com/user-attachments/assets/1e95d106-8f66-40ad-971b-1cba67e95510)
Además, realizo y completo el [Readme](https://github.com/alecuevas660/Proyecto-sistema-web-de-despacho/blob/main/README.md) con las instrucciones de como configurar, descargar e instalar cada ambiente para cada tipo de área

**Comment by MoisesFigueroaDeveloper** [comment]
Desde la ultima reunion se ha decidido cambiar la elección de tecnologías a usar para el proyecto. Se re-estructurara el repositorio y se adaptara las pró![Image](https://github.com/user-attachments/assets/fd9a8054-4fb5-44e9-9b75-8bfdb56050b0)
ximas tareas de la issues.
