### ISSUE TITLE
Desarrollar la estructura de navegación en los mockups.

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#73]

**Comment by javegaf** [comment]
No se cuenta con el proceso de creación de cada vista, pero si las evidencias de cada vista reportado en el caso [Diseñar el mockup de las vistas de la paginas. #69](https://github.com/alecuevas660/Proyecto-sistema-web-de-despacho/issues/69)
**Se adjunta imagen general del diseño de vistas**
![Image](https://github.com/user-attachments/assets/d756b0df-a39b-4b0f-b2aa-9ddc9ce98451)
