### ISSUE TITLE
Pagina estado de inventario(Front-End).

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#88]
La página de Estado de Inventario permite la visualización detallada del inventario actual, incluyendo el stock de cada producto, su categoría, alertas asociadas y la posibilidad de realizar búsquedas y filtros avanzados.

**Comment by felipevega-dev** [comment]
Creada la pagina de inventario., con categorias, barra de busqueda y filtros.
