### ISSUE TITLE
-Tabla de productos(Front-End).

### ISSUE THREAD

**Issue by MoisesFigueroaDeveloper** [alecuevas660/Proyecto-sistema-web-de-despacho#89]
- Una tabla que lista todos los productos, mostrando columnas como: nombre, categoría, stock actual, stock mínimo, y precio.
- Cada fila de producto debe tener opciones de edición y eliminación.

**Comment by felipevega-dev** [comment]
Crud completo de los productos y las categorias integradas completamente con sus respectivas validaciones, eliminar, editar y crear.
